apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: 637423224913.dkr.ecr.us-east-1.amazonaws.com/reservations:latest
          name: reservations
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3003'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3001'
            - name: HTTP_PORT
              value: '3004'
          ports:
            - containerPort: 3004
